### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by metin-atalay** [AAAstorga/firebase-provider#10]
I try to implement the ferno but I got the below error. Kindly advice.

![image](https://github.com/vapor-community/ferno/assets/9380512/e28fc1f8-d07c-4234-9528-43610ae01b88)

**Comment by metin-atalay** [comment]
[ WARNING ] Ferno.FernoError.requestFailed
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Ferno.FernoError.requestFailed

**Comment by metin-atalay** [comment]
fixed the issue

**Comment by colinmasters** [comment]
@metin-atalay can you share the fix? I have similar issues
