### ISSUE TITLE
Doesn't conform to JWT 3.0.0 release

### ISSUE THREAD

**Issue by martinlasek** [AAAstorga/firebase-provider#3]
If your project depends on JWT `3.0.0` and you also try using this (Ferno) package with it's dependency of JWT being `3.0.0-rc.2.1.1`, you'll end up having the highest thus JWT 3.0.0 fetched into your project.

This leads to Ferno not being able to compile because `Payload` no longer conforms to `JWTPayload`.

Currently it implements
```swift
struct Payload: JWTPayload {
  ...

  func verify() throws {
    try exp.verify()
  }
}
```

I haven't worked enough with JWT to create a mergable PR so I am not sure if this would even be a temporary fix for the current package implementation:
```swift
struct Payload: JWTPayload {
  ...

  func verify(using signer: JWTSigner) throws {
    try exp.verifyNotExpired()  // .verify() is deprecated
  }
}
```

But it conforms and compiles, obviously the `signer` passed into the function is never used, but this  *sounds* like it does what it is expected to do: verify.

**Comment by AAAstorga** [comment]
Thank you! Will update the library soon! 👍

**Comment by mhs2342** [comment]
Doesn't seem like a fix has been released

**Comment by simonmitchell** [comment]
@AAAstorga any chance of getting this updated? I'm happy to submit a PR from our fork!

**Comment by simonmitchell** [comment]
Have submitted the PR here https://github.com/vapor-community/ferno/pull/4 with @MartinLasek's suggested change!

**Comment by vzsg** [comment]
I haven't tried, but as painful this whole ordeal is, I merged and tagged 0.4.0 with it, so at least there's some movement. Please check if it works.

**Comment by simonmitchell** [comment]
Scared myself a bit there that I'd somehow broken things... turned out I just had to delete the `.build` folder to resolve some issues with SPM pulling the latest version! It's all working great now, thanks for merging 😊

**Comment by vzsg** [comment]
Thanks for the update :)
